version: "3.8"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

  backend-staffconnect:
    container_name: backend-staffconnect
    image: backend-staffconnect
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - ../backend:/app

volumes:
  mongo-data:
    driver: local
